USE EShop
 --COMMENT
 --Get all products
 Select * from Orders

--Get all productst that habve category id = 10
Select * from Product where CategoryId=10

--Get total cost pf products listed with categoryid =10
Select SUM(Cost) from Product where CategoryId=10

--Get Product name , cost from product table
Select Name,Cost from Product

--Save above as view

Create View vw_Product AS 
(Select Name,Cost from Product)

--see the above view result
Select * from vw_Product

--gET ALL PRODUCTS WITH NAME STARTING WITH K
Select * from Product where Name Like 'K%'

--Get products wiyth second letter as e
Select * from Product where Name Like '[a-z]e%'

--Get all products whose cost is greater than 2000
Select * from Product where Cost>2000

--Get all products whose cost is not equal to 5000
Select * from Product where Cost<>2000

--Select all products with names as Tshirts, iPhone,kurti
Select * from Product where Name in ('T-Shirts', 'Iphone 14','Kurti')

--Getall products having a category id matching in productcategory

Select * from Product where CategoryId IN (Select Id from ProductCategory)

Select [Name], [OrderId] from Customer,Orders where Customer.Id = Orders.CustomerId 

Select Sum(Cost) from Customer,Orders, Product where Orders.CustomerId = Customer.Id AND Orders.ProductId = Product.Id
AND Customer.Name = 'Eena'





--1.Get all customer details
Select Name from Customer 


--2. Get all customer orders,customerid , orderid
Select Product.Name, [CustomerId],[OrderId] FROM Orders, Customer,Product where Customer.Id=Orders.CustomerId AND Orders.ProductId = Product.Id

--3. tOTAL REVENUE GENERATED BY TINA
Select Sum(Cost) from Customer,Orders, Product where Orders.CustomerId = Customer.Id AND Orders.ProductId = Product.Id
AND Customer.Name = 'Tina'

--4. get order details for cost above 900
Select Name,Cost,[OrderId], Status,OrderDate from Orders,Product where Orders.ProductId=Product.Id AND Product.Cost>900

--5. Get Order Details for Dates between Oct 1, 2022 and Oct 30, 2022
Select Name,Cost,[OrderId], Status,OrderDate from Orders,Product where Orders.OrderDate between '2022-10-01' AND '2022-10-30'

--6. Get Customer Name, Product Name Purchased, Product Cost for all customers
--Select Customer.Name,Product.Name, Sum(Cost) from Customer,Product,Orders where Customer.Id = Orders.OrderId AND Product.Id = Orders.ProductId 

--7. Get All Customers that contain third letter as 'e' and last letter as 'a'
Select * from Customer where Name Like '__e%a'
